data "sops_file" "infra_secret" {
  source_file = "secret.sops.yaml"
}

#- proxmox
locals {
  pm_api_url = "https://192.168.1.197:8006/api2/json"
  # here we could make a tf-prov user only for tf with proper permisssion
  pm_user     = "root@pam"
  pm_password = data.sops_file.infra_secret.data["secret_pm_password"]

  server_1_password = data.sops_file.infra_secret.data["secret_node_server_1_password"]
  server_2_password = data.sops_file.infra_secret.data["secret_node_server_2_password"]
  server_3_password = data.sops_file.infra_secret.data["secret_node_server_3_password"]

  # agent_1_password  = data.sops_file.infra_secret.data["secret_node_agent_1_password"]
  # agent_2_password  = data.sops_file.infra_secret.data["secret_node_agent_2_password"]
  # agent_3_password  = data.sops_file.infra_secret.data["secret_node_agent_3_password"]

  template_vm = "L1-3-ubuntu"
  public_keys = <<EOF
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIQvpNskUO0Zy8kzwzuQrErLqEnkJkMMJ9sLD4MBcxWl 1autoWork apheon-arco-10-11-2022 local-passphrase-less
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL8HmDq8XAhfKLyZnw6UWY4JmHfIhzJkoBUX3/JviXkn apheon@L2-1-ansible-debops
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCysROD7ESg8Bvh71vdom9y+e8lorN+MNTakE2nAXJ2y/iE3/UrqqRB/x+ap4ZDriLeAwIha8QhaoomZyQ3ZIQVbQsd4iUO79Pa9lqOQ0R2HfkyppI0iwmHPsRYf+vHs5CC7Iz/q7APGZVYWOcBYz68dllSmm5PP86orApUYiXifS3UrX3k/4dHzo+CSxlUZjC0q6ed8W0IE2V0ITycqDwRsbu4OES41TCwLZK0djg9bDwjqFYX3pQlbj5kURxpgJ8Sxd247xQa668zLJU0+pGddx3osnuQeS9eh/T8xqar+F7sKyecmarSaA9Kyi0ylHYUSgBUG2T1QD4xmQdbDFruwyKfR1vHS9cUX+Oa1LTHlIJLErNATulzdipZLIDtcfvrtpsIUXP71/rkyZbgihMOjZk6xOsv7YSLua4Y7NWEy6cskG59HCK2sw2DhrjyJUekESVRo1OosnIkt7BPshZMfpXDcq99s4ogW4ZlGnI5RLPKL2qFimpw2+YbguqNUs0= Generated by Ansible role robertdebock.users
    EOF


  # sshkeys and ssh_forward_ip we already have them in vm template due to cloud-init
  k3s_nodes = {
    "server-vm1" = {
      node      = "osiris"
      id        = 110
      server    = true
      cores     = 2
      memory    = 5100
      size      = "50G"
      storage   = "S1_512gb"
      template  = local.template_vm
      sshkeys   = local.public_keys
      user      = "apheon"
      password  = local.server_1_password
      ipconfig0 = "ip=192.168.42.111/16,gw=192.168.1.1"
      # ssh_forward_ip = "192.168.255.1"
      hostname_ip = "192.168.42.111"
      hagroup     = "osiris-ha"
    },
    "server-vm2" = {
      node      = "osiris"
      id        = 111
      server    = true
      cores     = 2
      memory    = 5100
      size      = "50G"
      storage   = "S1_512gb"
      template  = local.template_vm
      sshkeys   = local.public_keys
      user      = "apheon"
      password  = local.server_2_password
      ipconfig0 = "ip=192.168.42.112/16,gw=192.168.1.1"
      # ssh_forward_ip = "192.168.255.2"
      hostname_ip = "192.168.42.112"

      hagroup = "osiris-ha"
    },
    "server-vm3" = {
      node      = "osiris"
      id        = 112
      server    = true
      cores     = 2
      memory    = 5100
      size      = "50G"
      storage   = "S1_512gb"
      template  = local.template_vm
      sshkeys   = local.public_keys
      user      = "apheon"
      password  = local.server_3_password
      ipconfig0 = "ip=192.168.42.113/16,gw=192.168.1.1"
      # ssh_forward_ip = "192.168.255.3"
      hostname_ip = "192.168.42.113"
      hagroup     = "osiris-ha"
    }

    #gpu passthrough is not possible . use baremetall

    # "agent-vm-4" = {
    #   node           = "osiris"
    #   id             = 113
    #   server         = false
    #   cores          = 1
    #   memory         = 5100
    #   size           = "50G"
    #   storage        = "S1_512gb"
    #   template       = local.template_vm
    #   # sshkeys        = local.public_keys
    #   user           = "apheon"
    #   password       = local.agent_1_password
    #   ipconfig0      = "ip=192.168.42.114/16,gw=192.168.1.1"
    #   # ssh_forward_ip = "192.168.255.6"
    #   hagroup        = "osiris-ha"
    # },
    # "agent-vm-5" = {
    #   node           = "osiris"
    #   id             = 114
    #   server         = false
    #   cores          = 1
    #   memory         = 5100
    #   size           = "50G"
    #   storage        = "S1_512gb"
    #   template       = local.template_vm
    #   # sshkeys        = local.public_keys
    #   user           = "apheon"
    #   password       = local.agent_2_password
    #   ipconfig0      = "ip=192.168.42.115/16,gw=192.168.1.1"
    #   # ssh_forward_ip = "192.168.255.7"
    #   hagroup        = "osiris-ha"
    # }
    # "agent-vm-6" = {
    #   node           = "osiris"
    #   id             = 115
    #   server         = false
    #   cores          = 1
    #   memory         = 5100
    #   size           = "50G"
    #   storage        = "S1_512gb"
    #   template       = local.template_vm
    #   # sshkeys        = local.public_keys
    #   user           = "apheon"
    #   password       = local.agent_3_password
    #   ipconfig0      = "ip=192.168.42.116/16,gw=192.168.1.1"
    #   # ssh_forward_ip = "192.168.255.8"
    #   hagroup        = "osiris-ha"
    # }
  }
}

# #- cloudflare
# locals {
#   cloudflare_email        = data.sops_file.infra_secret.data["secret_cloudflare_email"]
#   cloudflare_api_key      = data.sops_file.infra_secret.data["secret_cloudflare_api_key"]
#   cloudflare_home_zone_id = data.sops_file.infra_secret.data["secret_cloudflare_home_zone_id"]
# }

# #- static
# locals {
#   home_ipv4 = data.sops_file.infra_secret.data["secret_home_ipv4"]
# }
