# resource "local_sensitive_file" "age_key" {
#   filename          =  # Must be the same as $GOOGLE_APPLICATION_CREDENTIALS
#   content           =  #
# }

data "sops_file" "infra_secret" {
  source_file = "secret.sops.yaml"
  # depends_on  = [local_sensitive_file.age_key]
}

#- proxmox
locals {
  pm_api_url = "https://192.168.1.197:8006/api2/json"

  # here we could make a tf-prov user only for tf with proper permisssion
  pm_user     = "root@pam"
  pm_password = data.sops_file.infra_secret.data["secret_pm_password"]

  server_1_password = data.sops_file.infra_secret.data["secret_node_server_1_password"]


  template_vm = "L1-3-ubuntu"
  public_keys = <<EOF
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIQvpNskUO0Zy8kzwzuQrErLqEnkJkMMJ9sLD4MBcxWl 1autoWork apheon-arco-10-11-2022 local-passphrase-less
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL8HmDq8XAhfKLyZnw6UWY4JmHfIhzJkoBUX3/JviXkn apheon@L2-1-ansible-debops
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCysROD7ESg8Bvh71vdom9y+e8lorN+MNTakE2nAXJ2y/iE3/UrqqRB/x+ap4ZDriLeAwIha8QhaoomZyQ3ZIQVbQsd4iUO79Pa9lqOQ0R2HfkyppI0iwmHPsRYf+vHs5CC7Iz/q7APGZVYWOcBYz68dllSmm5PP86orApUYiXifS3UrX3k/4dHzo+CSxlUZjC0q6ed8W0IE2V0ITycqDwRsbu4OES41TCwLZK0djg9bDwjqFYX3pQlbj5kURxpgJ8Sxd247xQa668zLJU0+pGddx3osnuQeS9eh/T8xqar+F7sKyecmarSaA9Kyi0ylHYUSgBUG2T1QD4xmQdbDFruwyKfR1vHS9cUX+Oa1LTHlIJLErNATulzdipZLIDtcfvrtpsIUXP71/rkyZbgihMOjZk6xOsv7YSLua4Y7NWEy6cskG59HCK2sw2DhrjyJUekESVRo1OosnIkt7BPshZMfpXDcq99s4ogW4ZlGnI5RLPKL2qFimpw2+YbguqNUs0= Generated by Ansible role robertdebock.users
    EOF


  # sshkeys and ssh_forward_ip we already have them in vm template due to cloud-init
  k3s_nodes = {
    "expanse" = {
      node     = "pve2"
      id       = 116
      server   = true
      cores    = 2
      memory   = 6000
      size     = "50G"
      storage  = "S1_512gb"
      template = local.template_vm
      sshkeys  = local.public_keys
      user     = "ubuntu"
      password = local.server_1_password
      # ipconfig0      = "ip=192.168.42.80/16,gw=192.168.1.1"
      ipconfig0   = "ip=192.168.42.80/16"
      hostname_ip = "192.168.42.80"
      # hagroup        = "osiris-ha"
    }
  }
}
